### ISSUE TITLE
Arreglar etiqueta

### ISSUE THREAD

**Issue by JavierPA3** [iesgrancapitan-entornos/2022-23---practica-5-github---issues-AdrianGM02#1]
https://github.com/iesgrancapitan-entornos/2022-23---practica-5-github---issues-AdrianGM02/blob/2352674335b610e011239c771fb9c7bef9250bcd/index.html#L10

Tienes que cerrra bien la etiqueta con </h1> y poner bien el mensaje

**Comment by AdrianGM02** [comment]
OK

**Comment by AdrianGM02** [comment]
ARREGLADO
