### ISSUE TITLE
Arreglar etiqueta 

### ISSUE THREAD

**Issue by JavierPA3** [iesgrancapitan-entornos/2022-23---practica-5-github---issues-AdrianGM02#2]
https://github.com/iesgrancapitan-entornos/2022-23---practica-5-github---issues-AdrianGM02/blob/2352674335b610e011239c771fb9c7bef9250bcd/index.html#L11

 Tienes que cerrar bien la etiqueta con </p>

**Comment by AdrianGM02** [comment]
OK
