### ISSUE TITLE
Añadir descripción de la página web.

### ISSUE THREAD

**Issue by JavierPA3** [iesgrancapitan-entornos/2022-23---practica-5-github---issues-AdrianGM02#4]
https://github.com/iesgrancapitan-entornos/2022-23---practica-5-github---issues-AdrianGM02/blob/2352674335b610e011239c771fb9c7bef9250bcd/index.html#L12

Tienes que añadir información sobre la página web!

**Comment by AdrianGM02** [comment]
OK
